name: Mirroring to gitlab internal (gitlab.konneqt.io)

on:
  push:
    branches:
      - main
      - staging
      - develop
      - DEVOPS*
      - MKT*
      - mkt-updates
      - devops-86abmtje6

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch origin '+refs/heads/*:refs/remotes/origin/*'

      # - name: Checkout repository
      #   uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Push branches and tags to GitLab
        env:
          GITLAB_DOMAIN_INTERNAL: ${{ vars.GITLAB_DOMAIN_INTERNAL }}
          GITLAB_TOKEN_INTERNAL: ${{ secrets.GITLAB_TOKEN_INTERNAL }}
        run: |
          git remote remove gitlab || true
          GITLAB_REPO="https://oauth2:${GITLAB_TOKEN_INTERNAL}@${GITLAB_DOMAIN_INTERNAL}/konneqt/infra-team/konneqt-qscim-education-lp.git"
          git remote add gitlab "$GITLAB_REPO"
          # Push all branchs
          git for-each-ref --format='%(refname:short)' refs/heads/ | xargs -n1 git push gitlab
          # Push tags
          git push gitlab --tags

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: mirror 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.IMAGE_NAME }}:latest